services:
  # --- DỊCH VỤ BACKEND ---
  backend:
    build:
      context: ./server # Đường dẫn đến thư mục chứa Dockerfile của BE
    image: vinhsonvlog/bewebsite:latest
    container_name: be-website
    ports:
      - "5000:5000" # Map port máy thât 5000 vào port container 5000
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=change-this-to-a-strong-secret
      # Nếu có dùng Database thì thêm biến môi trường ở đây
    networks:
      - website-network

  # --- DỊCH VỤ FRONTEND ---
  frontend:
    build:
      context: ./client # Đường dẫn đến thư mục chứa Dockerfile của FE
    image: vinhsonvlog/fewebsite:latest
    container_name: fe-website
    ports:
      - "3000:80" # Map port máy thật 3000 vào port 80 của Nginx trong container
    depends_on:
      - backend # Chờ backend chạy xong rồi frontend mới chạy
    networks:
      - website-network

networks:
  website-network:
    driver: bridge
